# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cruising-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cruising-app
  pod 'Firebase/Core'

  target 'cruising-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
